site_name: Buzzd Docs
site_url: https://buzzd.chat
dev_addr: 0.0.0.0:8069

theme:
  name: material
  favicon: images/favicon.svg
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.path
    - navigation.top

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - blog:
  - privacy:
      concurrency: 1

nav:
  - Home:  https://buzzd.chat
  - Getting Started:
      - Windows: index.md
      - macOS: mac-os.md
      - Linux: linux.md
  - Downloads:
      - Yahoo! Messenger: downloads/yahoo-messenger.md
      - Flash Player: downloads/flash-player.md
      - BZDPatcher: downloads/bzd-patcher.md
  - FAQ: faq.md
  - Blog:
      - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/buzzd

    - icon: fontawesome/brands/tiktok
      link: https://tiktok.com/@buzzdchat

    - icon: fontawesome/brands/instagram
      link: https://instagram.com/buzzd.chat
