site_name: Buzzd Docs
site_url: https://buzzd.chat
dev_addr: 0.0.0.0:8069

repo_name: bogdannbv/buzzd-docs
repo_url: https://github.com/bogdannbv/buzzd-docs
edit_uri: edit/main/docs/

copyright: "Copyright &copy; 2024 - 2025 Bogdan Nicorici"

theme:
  name: material
  favicon: images/favicon.svg
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.path
    - navigation.top
    - content.action.edit
    - search.highlight

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - blog:
  - search:

  - privacy:
      concurrency: 1
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

nav:
  - Home:  https://buzzd.chat
  - Getting Started:
      - Windows: index.md
      - macOS: mac-os.md
      - Linux: linux.md
  - Downloads:
      - Yahoo! Messenger: downloads/yahoo-messenger.md
      - Flash Player: downloads/flash-player.md
      - BZDPatcher: downloads/bzd-patcher.md
  - FAQ: faq.md
  - Blog:
      - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/buzzd
      name: Join us on Discord

    - icon: fontawesome/brands/tiktok
      link: https://tiktok.com/@buzzdchat
      name: Buzzd on TikTok

    - icon: fontawesome/brands/instagram
      link: https://instagram.com/buzzd.chat
      name: Buzzd on Instagram
