name: Build and deploy documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material:9.6
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build documentation
        run: |
          mkdocs build --clean

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: site
          retention-days: 1

  deploy:
    name: Deploy to GH pages
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:

      - name: Download docs artifact
        uses: actions/download-artifact@v5
        with:
          name: docs

      - name: LS
        run: |
          ls -alh

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
